import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "@/lib/contexts/authContext";
import NavBar from "@/components/general/navBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-background-50 flex flex-col items-center`}
      >
        <AuthContextProvider>
          <NavBar />
          <h1 className="font-heading text-8xl text-accent-800">Talon Games</h1>
          <div className="w-5/6 ml-auto mr-auto">{children}</div>
        </AuthContextProvider>
        <footer className="bg-accent-100 rounded-xl p-5 mb-4 w-5/6 flex justify-between">
          <a
            href="https://github.com/cqb13/talon-games/blob/main/LICENSE"
            className="hover:text-secondary-600 transition-all duration-200 ease-in-out"
            target="_blank"
          >
            Copyright © 2024
          </a>
          <a
            href="https://maksimstraus.dev"
            className="hover:text-secondary-600 transition-all duration-200 ease-in-out"
            target="_blank"
          >
            Created by: Maksim Straus
          </a>
        </footer>
      </body>
    </html>
  );
}
